// Generated by gencpp from file motoman_hc10_moveit_config/ControlYakuzaMsg.msg
// DO NOT EDIT!


#ifndef MOTOMAN_HC10_MOVEIT_CONFIG_MESSAGE_CONTROLYAKUZAMSG_H
#define MOTOMAN_HC10_MOVEIT_CONFIG_MESSAGE_CONTROLYAKUZAMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motoman_hc10_moveit_config
{
template <class ContainerAllocator>
struct ControlYakuzaMsg_
{
  typedef ControlYakuzaMsg_<ContainerAllocator> Type;

  ControlYakuzaMsg_()
    : type(0)  {
    }
  ControlYakuzaMsg_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef int32_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ControlYakuzaMsg_

typedef ::motoman_hc10_moveit_config::ControlYakuzaMsg_<std::allocator<void> > ControlYakuzaMsg;

typedef boost::shared_ptr< ::motoman_hc10_moveit_config::ControlYakuzaMsg > ControlYakuzaMsgPtr;
typedef boost::shared_ptr< ::motoman_hc10_moveit_config::ControlYakuzaMsg const> ControlYakuzaMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator1> & lhs, const ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator1> & lhs, const ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motoman_hc10_moveit_config

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bda37decd5e3814bcc042f341d2e60a1";
  }

  static const char* value(const ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbda37decd5e3814bULL;
  static const uint64_t static_value2 = 0xcc042f341d2e60a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motoman_hc10_moveit_config/ControlYakuzaMsg";
  }

  static const char* value(const ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 type\n"
;
  }

  static const char* value(const ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlYakuzaMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motoman_hc10_moveit_config::ControlYakuzaMsg_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOMAN_HC10_MOVEIT_CONFIG_MESSAGE_CONTROLYAKUZAMSG_H
